### ISSUE TITLE
URL's not working correctly

### ISSUE THREAD

**Issue by keesse** [ralsina/markterm#1]
Hi ralsina, 

I just build markterm and it works fine, so thanks!
However when clicking on the shown URL's in the terminal, I get a 404, this is because there is a ">" added, when I remove this, I get the correct page.
E.g. https://github.com/charmbracelet/glow%3E

Regards,

kees

**Comment by ralsina** [comment]
Thanksfor the report, I'll take a look!

**Comment by ralsina** [comment]
They seem to be working for me right now, maybe I fixed it at some point :-D  

Could you check with the latest code from main? If that works I will make another release.

**Comment by keesse** [comment]
I did a `git pull origin main` to update the source directory, but make
gave an error, so I tried a new clone after removing the old directory, but
with the same result:

markterm on  main is 📦 v0.3.0 via 🔮 v1.13.1
❯ make
shards build -Dstrict_multi_assign -Dno_number_autocast
Resolving dependencies
Fetching https://github.com/ralsina/tartrazine.git
Fetching https://github.com/ralsina/sixteen.git
Fetching https://github.com/icyleaf/markd.git
Fetching https://github.com/chenkovsky/docopt.cr.git
Fetching https://github.com/schovi/baked_file_system.git
Fetching https://github.com/crystal-china/base58.cr.git
Installing markd (0.5.0)
Installing baked_file_system (0.10.0)
Installing base58 (0.1.0 at 2b0564a)
Installing sixteen (0.3.0)
Installing docopt (0.2.0 at 620fce4)
Installing tartrazine (0.6.1)
Writing shard.lock
Building: markterm
Error target markterm failed to compile:
Showing last frame. Use --error-trace for full trace.

In src/terminal.cr:100:30

 100 | formatter.format(source, lexer)
                                ^----
Error: expected argument #2 to 'Tartrazine::Ansi#format' to be
Tartrazine::Lexer, not Tartrazine::BaseLexer

Overloads are:
 - Tartrazine::Ansi#format(text : String, lexer : BaseLexer, outp : IO)
 - Tartrazine::Ansi#format(text : String, lexer : Lexer)
 - Tartrazine::Formatter#format(text : String, lexer : Lexer)

make: *** [Makefile:2: build] Error 1




Op ma 26 aug 2024 om 17:34 schreef Roberto Alsina ***@***.***

**Comment by ralsina** [comment]
Ok, pushed a new release of tartrazine and a new commit in markterm, this combination should work :-)

**Comment by keesse** [comment]
Unfortunately not

markterm on  main is 📦 v0.3.0 via 🔮 v1.13.2 took 2m31s 
❯ git pull origin main 
remote: Enumerating objects: 5, done.
remote: Counting objects: 100% (5/5), done.
remote: Compressing objects: 100% (1/1), done.
remote: Total 3 (delta 2), reused 3 (delta 2), pack-reused 0 (from 0)
Unpacking objects: 100% (3/3), 333 bytes | 333.00 KiB/s, done.
From https://github.com/ralsina/markterm
 * branch            main       -> FETCH_HEAD
   f69a123..7d5a142  main       -> origin/main
Updating f69a123..7d5a142
Fast-forward
 shard.yml | 1 +
 1 file changed, 1 insertion(+)

markterm on  main is 📦 v0.3.0 via 🔮 v1.13.2 
❯ make
shards build -Dstrict_multi_assign -Dno_number_autocast
Resolving dependencies
Fetching https://github.com/icyleaf/markd.git
Fetching https://github.com/chenkovsky/docopt.cr.git
Fetching https://github.com/ralsina/tartrazine.git
Fetching https://github.com/ralsina/sixteen.git
Fetching https://github.com/schovi/baked_file_system.git
Fetching https://github.com/crystal-china/base58.cr.git
Unable to satisfy the following requirements:

- `sixteen (branch main)` required by `shard.yml`
- `sixteen (0.3.0)` required by `shard.lock`
- `sixteen (*)` required by `tartrazine 0.6.1`
Failed to resolve dependencies
make: *** [Makefile:2: build] Error 1

**Comment by ralsina** [comment]
remove your lib/ and shard.lock first

**Comment by ralsina** [comment]
And sorry about all the complications, but hey, you are AFAIK the second person to try this :-D

**Comment by keesse** [comment]
Removing the shard.lock did it, I could build.
However from the terminal I am using [Hyper](https://hyper.is/) gave the same problem, I then tried [Warp](https://www.warp.dev/), **that worked!**
Tried the standard Linux Mint Terminal, that gave errors, also Terminator, appearingly they do not support links

markterm on  main is 📦 v0.3.0 via 🔮 v1.13.2 
❯ bin/markterm README.md 
Unhandled exception: Missing ENV key: "TERM_PROGRAM" (KeyError)
  from /home/kees/.asdf/installs/crystal/1.13.2/share/crystal/src/env.cr:57:7 in 'fetch'
  from /home/kees/.asdf/installs/crystal/1.13.2/share/crystal/src/env.cr:22:5 in '[]'
  from src/terminal.cr:8:8 in 'supports_links?'
  from src/markterm.cr:183:14 in 'text'
  from lib/markd/src/markd/renderer.cr:92:13 in 'render'
  from src/markterm.cr:203:7 in 'render'
  from src/markterm.cr:212:5 in 'to_term:theme:code_theme'
  from src/main.cr:21:8 in 'main'
  from src/main.cr:32:1 in '__crystal_main'
  from /home/kees/.asdf/installs/crystal/1.13.2/share/crystal/src/crystal/main.cr:118:5 in 'main_user_code'
  from /home/kees/.asdf/installs/crystal/1.13.2/share/crystal/src/crystal/main.cr:104:7 in 'main'
  from /home/kees/.asdf/installs/crystal/1.13.2/share/crystal/src/crystal/main.cr:130:3 in 'main'
  from /lib/x86_64-linux-gnu/libc.so.6 in '??'
  from /lib/x86_64-linux-gnu/libc.so.6 in '__libc_start_main'
  from bin/markterm in '_start'
  from ???

**Comment by ralsina** [comment]
Ok, the support for html-style links in different terminals is ... spotty?

I tried it in kitty and alacritty, will check on a few of the ones you mentioned.

**Comment by ralsina** [comment]
I tried hyper. Markterm is not even trying to do links in it!

What hyper does is recognize URL patterns but it reads `<https://foo.com>` as a link to `https://foo.com>` which is different from any other terminal.

For terminator (and probably other VTE based terminals) it´s a bug in markterm I can fix tonight

You have been really helpful dude!

**Comment by ralsina** [comment]
Fixed in master for terminator (and probbaly for mint too)

For hyper I created an issue because it looks like a bug: https://github.com/vercel/hyper/issues/8031

If you find any other weird behaviour just open another issue.

**Comment by keesse** [comment]
A shard version issue with tartrazine (I did remove shard.lock)

markterm on  main is 📦 v0.3.0 via 🔮 v1.13.2 
❯ git pull origin main  
remote: Enumerating objects: 27, done.
remote: Counting objects: 100% (27/27), done.
remote: Compressing objects: 100% (10/10), done.
remote: Total 21 (delta 12), reused 20 (delta 11), pack-reused 0 (from 0)
Unpacking objects: 100% (21/21), 3.56 KiB | 145.00 KiB/s, done.
From https://github.com/ralsina/markterm
 * branch            main       -> FETCH_HEAD
   7d5a142..c4617e3  main       -> origin/main
Updating 7d5a142..c4617e3
Fast-forward
 .pre-commit-config.yaml | 35 +++++++++++++++++++++++++++++++++++
 CHANGELOG.md            |  5 +++++
 Makefile                | 16 ++++++++++++++++
 README.md               |  9 ++++-----
 cliff.toml              | 79 +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
 shard.yml               |  2 +-
 src/terminal.cr         |  2 +-
 7 files changed, 141 insertions(+), 7 deletions(-)
 create mode 100644 .pre-commit-config.yaml
 create mode 100644 CHANGELOG.md
 create mode 100644 cliff.toml

markterm on  main is 📦 v0.3.1 via 🔮 v1.13.2 
❯ make
shards build -Dstrict_multi_assign -Dno_number_autocast
Resolving dependencies
Fetching https://github.com/chenkovsky/docopt.cr.git
Fetching https://github.com/ralsina/tartrazine.git
Fetching https://github.com/ralsina/sixteen.git
Fetching https://github.com/icyleaf/markd.git
Fetching https://github.com/ralsina/baked_file_system.git
Fetching https://github.com/crystal-china/base58.cr.git
Shard "tartrazine" version (0.6.1) doesn't match tag version (0.6.3)
Using markd (0.5.0)
Using baked_file_system (0.10.0 at beb3731)
Using base58 (0.1.0 at 2b0564a)
Installing sixteen (0.3.0 at b133e02)
Using docopt (0.2.0 at 620fce4)
Using tartrazine (0.6.3)
Writing shard.lock
Building: markterm

markterm on  main is 📦 v0.3.1 via 🔮 v1.13.2 took 12s 
❯ ll bin
totaal 8128
drwxrwxr-x 2 kees kees       0 aug 27 16:39 .
drwxrwxr-x 7 kees kees       0 aug 27 16:38 ..
-rwxrwxr-x 1 kees kees 6420160 aug 27 16:39 markterm

markterm on  main is 📦 v0.3.1 via 🔮 v1.13.2 
❯ bin/markterm README.md 
Unhandled exception: Unknown lexer: docopt (Exception)
  from lib/tartrazine/src/lexer.cr:30:5 in 'lexer_by_name'
  from lib/tartrazine/src/lexer.cr:13:12 in 'lexer'
  from src/terminal.cr:99:13 in 'highlight'
  from src/markterm.cr:63:16 in 'code_block'
  from lib/markd/src/markd/renderer.cr:70:13 in 'render'
  from src/markterm.cr:203:7 in 'render'
  from src/markterm.cr:212:5 in 'to_term:theme:code_theme'
  from src/main.cr:21:8 in 'main'
  from src/main.cr:32:1 in '__crystal_main'
  from /home/kees/.asdf/installs/crystal/1.13.2/share/crystal/src/crystal/main.cr:118:5 in 'main_user_code'
  from /home/kees/.asdf/installs/crystal/1.13.2/share/crystal/src/crystal/main.cr:104:7 in 'main'
  from /home/kees/.asdf/installs/crystal/1.13.2/share/crystal/src/crystal/main.cr:130:3 in 'main'
  from /lib/x86_64-linux-gnu/libc.so.6 in '??'
  from /lib/x86_64-linux-gnu/libc.so.6 in '__libc_start_main'
  from bin/markterm in '_start'
  from ???

**Comment by ralsina** [comment]
The warning is harmless.

I'll do a fix for the error tonight.

**Comment by ralsina** [comment]
Version 0.3.2 with the fix is now out.

**Comment by keesse** [comment]
I did a pull and the Makefile disappeared!
Copied it from an old directory and could build.
The build indeed worked in the Mint Terminal and Terminator with Ctrl+Left mouse button, like you wrote not in Hyper

markterm on  main is 📦 v0.3.1 via 🔮 v1.13.2 
❯ git pull origin main
remote: Enumerating objects: 36, done.
remote: Counting objects: 100% (36/36), done.
remote: Compressing objects: 100% (12/12), done.
remote: Total 28 (delta 17), reused 27 (delta 16), pack-reused 0 (from 0)
Unpacking objects: 100% (28/28), 3.56 KiB | 113.00 KiB/s, done.
From https://github.com/ralsina/markterm
 * branch            main       -> FETCH_HEAD
   c4617e3..8b88a5c  main       -> origin/main
Updating c4617e3..8b88a5c
Fast-forward
 .gitignore      |  1 +
 CHANGELOG.md    | 22 ++++++++++++++++++++++
 Hacefile.yml    | 91 +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
 Makefile        | 23 -----------------------
 README.md       |  1 +
 build_static.sh |  4 ++--
 do_release.sh   | 15 +++++++++++++++
 shard.yml       |  6 +++++-
 src/terminal.cr |  6 +++++-
 9 files changed, 142 insertions(+), 27 deletions(-)
 create mode 100644 Hacefile.yml
 delete mode 100644 Makefile
 create mode 100755 do_release.sh

**Comment by ralsina** [comment]
I am migrating from Makefiles to a different tool. You can always build
using "shards build" anyway. I just updated the build instructions to say
that.

**Comment by keesse** [comment]
Hi Robert,

I did a new `git clone` and a `shards build`, that worked fine, only I
still got:
Shard "tartrazine" version (0.6.1) doesn't match tag version (0.6.3)

Should you change the version number in lib/tartrzine/shards.yml from 0.6.1
to 0.6.3?

P.s. I have a *feature request:* paging
When I page the output throught less, I lose the colors, so if you can
build in some form of paging, that would be great!

Regards,

Kees

Op di 27 aug 2024 om 23:40 schreef Roberto Alsina ***@***.***
>:

> I am migrating from Makefiles to a different tool. You can always build
> using "shards build" anyway. I just updated the build instructions to say
> that.
>

**Comment by ralsina** [comment]
On Wed, Aug 28, 2024 at 4:21 PM Kees ***@***.***> wrote:

> Hi Robert,
>
> I did a new `git clone` and a `shards build`, that worked fine, only I
> still got:
> Shard "tartrazine" version (0.6.1) doesn't match tag version (0.6.3)
>
> Should you change the version number in lib/tartrzine/shards.yml from
> 0.6.1
> to 0.6.3?
>
> It's already changed, no worries, it will settle on a future release.



> P.s. I have a *feature request:* paging
> When I page the output throught less, I lose the colors, so if you can
> build in some form of paging, that would be great!


Using `less -R` should work but doesn't because of something I can fix.
Next version will work.


>
>
> Regards,
>
> Kees
>
> Op di 27 aug 2024 om 23:40 schreef Roberto Alsina ***@***.***
> >:
>
> > I am migrating from Makefiles to a different tool. You can always build
> > using "shards build" anyway. I just updated the build instructions to
> say
> > that.
> >

**Comment by ralsina** [comment]
It was a one-liner and I have automated releases, so just did a quick one now, remember to use `less -R` so it shows color.

**Comment by keesse** [comment]
`less -R` does not show any colors, except the tick-boxes, at my system on
all different terminals

Op wo 28 aug 2024 om 22:35 schreef Roberto Alsina ***@***.***

**Comment by ralsina** [comment]
It does with the latest version :-)

[image: image.png]

**Comment by keesse** [comment]
Yes, see my reply on the Forum.
Thanks!
Met vriendelijke groeten,

Kees Serier

30 aug. 2024 13:07:38 Roberto Alsina ***@***.***>:

> 
> It does with the latest version :-)
> 
> [image: image.png]
>
